### ISSUE TITLE
CoreImageFilter sample app no longer works

### ISSUE THREAD

**Issue by ghost** [KevinDoughty/AdditiveSamples#1]
On the latest version of Xcode (7.2.1) and OS X (10.11.3), the CoreImageFilter demo app no longer does anything when you interact with the image. Clicking around doesn't apply any sort of filter.

**Comment by ghost** [comment]
Ah. Apparently OS X added a little flag specifically for this case? Seems weird:

`self.layerUsesCoreImageFilters = YES;`

That fixes it.

**Comment by KevinDoughty** [comment]
Fixed! Thanks for the tip. The image quality has dropped significantly though... pixels do not get blended anymore.

**Comment by ghost** [comment]
What do you mean? Could it have to do with not using a compositing filter?

**Comment by KevinDoughty** [comment]
I can't speculate why.
